"""initial_schema

Revision ID: 26f1c3cac4bc
Revises: 
Create Date: 2026-09-06 18:45:11.116105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26f1c3cac4bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_template',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('html_body', sa.Text(), nullable=False),
    sa.Column('text_body', sa.Text(), nullable=False),
    sa.Column('available_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_template_slug'), 'email_template', ['slug'], unique=True)
    op.create_table('platform_payment_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('phone_label', sa.String(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('qr_image_url', sa.String(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('platform_fee_percent', sa.Numeric(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('contractor', 'musician', 'admin', name='userrole'), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('email_verification_token', sa.String(), nullable=True),
    sa.Column('email_verification_expires_at', sa.DateTime(), nullable=True),
    sa.Column('password_reset_token', sa.String(), nullable=True),
    sa.Column('password_reset_expires_at', sa.DateTime(), nullable=True),
    sa.Column('terms_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('terms_accepted_ip', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_email_verification_token'), 'user', ['email_verification_token'], unique=True)
    op.create_index(op.f('ix_user_password_reset_token'), 'user', ['password_reset_token'], unique=True)
    op.create_table('contractor_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('preferences', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('document_number', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('id_document_url', sa.String(), nullable=True),
    sa.Column('contract_template_title', sa.String(), nullable=True),
    sa.Column('contract_template_body', sa.String(), nullable=True),
    sa.Column('contract_pdf_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending_review', 'published', 'rejected', name='profilestatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('rating_avg', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('email_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_slug', sa.String(), nullable=False),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('provider_message_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_log_created_at'), 'email_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_log_recipient'), 'email_log', ['recipient'], unique=False)
    op.create_index(op.f('ix_email_log_status'), 'email_log', ['status'], unique=False)
    op.create_index(op.f('ix_email_log_template_slug'), 'email_log', ['template_slug'], unique=False)
    op.create_index(op.f('ix_email_log_user_id'), 'email_log', ['user_id'], unique=False)
    op.create_table('ensemble_member',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('leader_user_id', sa.UUID(), nullable=False),
    sa.Column('member_user_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('specialties', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('invited', 'active', 'inactive', name='ensemblememberstatus'), nullable=False),
    sa.Column('password_setup_token', sa.String(), nullable=True),
    sa.Column('password_setup_expires_at', sa.DateTime(), nullable=True),
    sa.Column('invited_at', sa.DateTime(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['leader_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('leader_user_id', 'email', name='uq_ensemble_member_leader_email')
    )
    op.create_index(op.f('ix_ensemble_member_email'), 'ensemble_member', ['email'], unique=False)
    op.create_index(op.f('ix_ensemble_member_leader_user_id'), 'ensemble_member', ['leader_user_id'], unique=False)
    op.create_index(op.f('ix_ensemble_member_member_user_id'), 'ensemble_member', ['member_user_id'], unique=False)
    op.create_index(op.f('ix_ensemble_member_password_setup_token'), 'ensemble_member', ['password_setup_token'], unique=True)
    op.create_table('musician_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stage_name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('instruments', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('songs', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('repertoire', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price_per_hour', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_per_event', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('portfolio_description', sa.String(), nullable=True),
    sa.Column('location_city', sa.String(), nullable=True),
    sa.Column('location_zone', sa.String(), nullable=True),
    sa.Column('availability_type', sa.Enum('hourly', 'per_event', 'both', name='availabilitytype'), nullable=False),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('gallery_images', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('videos', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('showreel_video_url', sa.String(), nullable=True),
    sa.Column('instagram_url', sa.String(), nullable=True),
    sa.Column('facebook_url', sa.String(), nullable=True),
    sa.Column('tiktok_url', sa.String(), nullable=True),
    sa.Column('youtube_channel_url', sa.String(), nullable=True),
    sa.Column('spotify_url', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('id_document_url', sa.String(), nullable=True),
    sa.Column('contract_template_title', sa.String(), nullable=True),
    sa.Column('contract_template_body', sa.Text(), nullable=True),
    sa.Column('contract_pdf_url', sa.String(), nullable=True),
    sa.Column('signature_image_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending_review', 'published', 'rejected', name='profilestatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('rating_avg', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('google', 'facebook', name='oauthprovider'), nullable=False),
    sa.Column('provider_user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_oauth_provider_user')
    )
    op.create_index(op.f('ix_oauth_account_user_id'), 'oauth_account', ['user_id'], unique=False)
    op.create_table('support_ticket',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('guest_name', sa.String(), nullable=True),
    sa.Column('guest_email', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', name='supportticketstatus'), nullable=False),
    sa.Column('admin_response', sa.Text(), nullable=True),
    sa.Column('responded_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_ip', sa.String(), nullable=True),
    sa.Column('submitted_user_agent', sa.String(), nullable=True),
    sa.Column('submitted_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['responded_by_admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_ticket_user_id'), 'support_ticket', ['user_id'], unique=False)
    op.create_table('booking',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contractor_id', sa.UUID(), nullable=True),
    sa.Column('musician_id', sa.UUID(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('location_address', sa.String(), nullable=False),
    sa.Column('location_city', sa.String(), nullable=True),
    sa.Column('location_reference', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_description', sa.String(), nullable=True),
    sa.Column('requested_repertoire', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('price_agreed', sa.Numeric(), nullable=True),
    sa.Column('advance_amount', sa.Numeric(), nullable=True),
    sa.Column('platform_fee_percent', sa.Numeric(), nullable=True),
    sa.Column('platform_fee_amount', sa.Numeric(), nullable=True),
    sa.Column('musician_quote_notes', sa.String(), nullable=True),
    sa.Column('quoted_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('cancelled_by', sa.String(), nullable=True),
    sa.Column('pending_location_address', sa.String(), nullable=True),
    sa.Column('pending_location_city', sa.String(), nullable=True),
    sa.Column('pending_location_reference', sa.String(), nullable=True),
    sa.Column('pending_event_description', sa.String(), nullable=True),
    sa.Column('pending_change_notes', sa.String(), nullable=True),
    sa.Column('pending_price_agreed', sa.Numeric(), nullable=True),
    sa.Column('pending_advance_amount', sa.Numeric(), nullable=True),
    sa.Column('change_requested_by', sa.String(), nullable=True),
    sa.Column('change_requested_at', sa.DateTime(), nullable=True),
    sa.Column('share_token', sa.String(), nullable=True),
    sa.Column('share_enabled', sa.Boolean(), nullable=False),
    sa.Column('share_enabled_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('requested', 'accepted', 'contract_pending', 'contract_signed', 'payment_pending', 'payment_retained', 'change_pending', 'balance_pending', 'balance_review', 'in_progress', 'payment_released', 'completed', 'cancelled', name='bookingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor_profile.id'], ),
    sa.ForeignKeyConstraint(['musician_id'], ['musician_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_share_token'), 'booking', ['share_token'], unique=True)
    op.create_table('musician_availability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('musician_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['musician_id'], ['musician_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('musician_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('musician_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('image', 'video', 'audio', name='mediatype'), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['musician_id'], ['musician_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_location_participant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('sharing', sa.Boolean(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'user_id', name='uq_booking_location_participant_booking_user')
    )
    op.create_index(op.f('ix_booking_location_participant_booking_id'), 'booking_location_participant', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_location_participant_user_id'), 'booking_location_participant', ['user_id'], unique=False)
    op.create_table('booking_location_ping',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('party', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_location_ping_booking_id'), 'booking_location_ping', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_location_ping_created_at'), 'booking_location_ping', ['created_at'], unique=False)
    op.create_index(op.f('ix_booking_location_ping_user_id'), 'booking_location_ping', ['user_id'], unique=False)
    op.create_table('booking_location_share',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('musician_sharing', sa.Boolean(), nullable=False),
    sa.Column('contractor_sharing', sa.Boolean(), nullable=False),
    sa.Column('musician_requested_at', sa.DateTime(), nullable=True),
    sa.Column('contractor_requested_at', sa.DateTime(), nullable=True),
    sa.Column('musician_requested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('contractor_requested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('musician_lat', sa.Float(), nullable=True),
    sa.Column('musician_lng', sa.Float(), nullable=True),
    sa.Column('musician_accuracy', sa.Float(), nullable=True),
    sa.Column('musician_updated_at', sa.DateTime(), nullable=True),
    sa.Column('contractor_lat', sa.Float(), nullable=True),
    sa.Column('contractor_lng', sa.Float(), nullable=True),
    sa.Column('contractor_accuracy', sa.Float(), nullable=True),
    sa.Column('contractor_updated_at', sa.DateTime(), nullable=True),
    sa.Column('event_lat', sa.Float(), nullable=True),
    sa.Column('event_lng', sa.Float(), nullable=True),
    sa.Column('event_address', sa.String(), nullable=True),
    sa.Column('event_city', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contractor_requested_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['musician_requested_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_location_share_booking_id'), 'booking_location_share', ['booking_id'], unique=True)
    op.create_table('booking_member_invite',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('ensemble_member_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', name='bookingmemberinvitestatus'), nullable=False),
    sa.Column('response_token', sa.String(), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ensemble_member_id'], ['ensemble_member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'ensemble_member_id', name='uq_booking_member_invite')
    )
    op.create_index(op.f('ix_booking_member_invite_booking_id'), 'booking_member_invite', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_member_invite_ensemble_member_id'), 'booking_member_invite', ['ensemble_member_id'], unique=False)
    op.create_index(op.f('ix_booking_member_invite_response_token'), 'booking_member_invite', ['response_token'], unique=True)
    op.create_table('booking_member_payout',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('ensemble_member_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'locked', 'paid', name='bookingmemberpayoutstatus'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('set_by_leader_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ensemble_member_id'], ['ensemble_member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'ensemble_member_id', name='uq_booking_member_payout')
    )
    op.create_index(op.f('ix_booking_member_payout_booking_id'), 'booking_member_payout', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_member_payout_ensemble_member_id'), 'booking_member_payout', ['ensemble_member_id'], unique=False)
    op.create_table('booking_message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('sender_user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_review',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=True),
    sa.Column('guest_name', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('photo_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('video_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_review_booking_id'), 'booking_review', ['booking_id'], unique=False)
    op.create_table('contract',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contract_pdf_url', sa.String(), nullable=True),
    sa.Column('contract_signed_pdf_url', sa.String(), nullable=True),
    sa.Column('contractor_signature_url', sa.String(), nullable=True),
    sa.Column('musician_signature_url', sa.String(), nullable=True),
    sa.Column('terms_version', sa.Integer(), nullable=True),
    sa.Column('contractor_signed', sa.Boolean(), nullable=True),
    sa.Column('musician_signed', sa.Boolean(), nullable=True),
    sa.Column('terms_accepted', sa.Boolean(), nullable=True),
    sa.Column('terms_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('terms_accepted_ip', sa.String(), nullable=True),
    sa.Column('contractor_sign_timestamp', sa.DateTime(), nullable=True),
    sa.Column('musician_sign_timestamp', sa.DateTime(), nullable=True),
    sa.Column('contractor_sign_ip', sa.String(), nullable=True),
    sa.Column('musician_sign_ip', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_table('contractor_recommendation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('musician_id', sa.UUID(), nullable=False),
    sa.Column('contractor_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['musician_id'], ['musician_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', name='uq_contractor_recommendation_booking')
    )
    op.create_index(op.f('ix_contractor_recommendation_booking_id'), 'contractor_recommendation', ['booking_id'], unique=False)
    op.create_index(op.f('ix_contractor_recommendation_contractor_id'), 'contractor_recommendation', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_contractor_recommendation_musician_id'), 'contractor_recommendation', ['musician_id'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('payment_type', sa.String(), nullable=True),
    sa.Column('evidence_url', sa.String(), nullable=True),
    sa.Column('evidence_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('initiated', 'retained', 'released', 'refunded', 'failed', 'rejected', name='paymentstatus'), nullable=True),
    sa.Column('retained_at', sa.DateTime(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_complaint',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('opened_by_user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('open', 'musician_accepted', 'musician_responded', 'settled', name='bookingcomplaintstatus'), nullable=False),
    sa.Column('musician_response', sa.Text(), nullable=True),
    sa.Column('musician_response_evidence_url', sa.String(), nullable=True),
    sa.Column('musician_responded_at', sa.DateTime(), nullable=True),
    sa.Column('admin_musician_amount', sa.Numeric(), nullable=True),
    sa.Column('admin_contractor_refund', sa.Numeric(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('settled_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('refund_status', sa.String(), nullable=False),
    sa.Column('refund_evidence_url', sa.String(), nullable=True),
    sa.Column('refund_sent_at', sa.DateTime(), nullable=True),
    sa.Column('refund_sent_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('refund_validated_at', sa.DateTime(), nullable=True),
    sa.Column('refund_rejection_reason', sa.Text(), nullable=True),
    sa.Column('refund_payment_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['opened_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['refund_payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['refund_sent_by_admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['settled_by_admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_complaint_booking_id'), 'booking_complaint', ['booking_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_complaint_booking_id'), table_name='booking_complaint')
    op.drop_table('booking_complaint')
    op.drop_table('payment')
    op.drop_index(op.f('ix_contractor_recommendation_musician_id'), table_name='contractor_recommendation')
    op.drop_index(op.f('ix_contractor_recommendation_contractor_id'), table_name='contractor_recommendation')
    op.drop_index(op.f('ix_contractor_recommendation_booking_id'), table_name='contractor_recommendation')
    op.drop_table('contractor_recommendation')
    op.drop_table('contract')
    op.drop_index(op.f('ix_booking_review_booking_id'), table_name='booking_review')
    op.drop_table('booking_review')
    op.drop_table('booking_message')
    op.drop_index(op.f('ix_booking_member_payout_ensemble_member_id'), table_name='booking_member_payout')
    op.drop_index(op.f('ix_booking_member_payout_booking_id'), table_name='booking_member_payout')
    op.drop_table('booking_member_payout')
    op.drop_index(op.f('ix_booking_member_invite_response_token'), table_name='booking_member_invite')
    op.drop_index(op.f('ix_booking_member_invite_ensemble_member_id'), table_name='booking_member_invite')
    op.drop_index(op.f('ix_booking_member_invite_booking_id'), table_name='booking_member_invite')
    op.drop_table('booking_member_invite')
    op.drop_index(op.f('ix_booking_location_share_booking_id'), table_name='booking_location_share')
    op.drop_table('booking_location_share')
    op.drop_index(op.f('ix_booking_location_ping_user_id'), table_name='booking_location_ping')
    op.drop_index(op.f('ix_booking_location_ping_created_at'), table_name='booking_location_ping')
    op.drop_index(op.f('ix_booking_location_ping_booking_id'), table_name='booking_location_ping')
    op.drop_table('booking_location_ping')
    op.drop_index(op.f('ix_booking_location_participant_user_id'), table_name='booking_location_participant')
    op.drop_index(op.f('ix_booking_location_participant_booking_id'), table_name='booking_location_participant')
    op.drop_table('booking_location_participant')
    op.drop_table('musician_media')
    op.drop_table('musician_availability')
    op.drop_index(op.f('ix_booking_share_token'), table_name='booking')
    op.drop_table('booking')
    op.drop_index(op.f('ix_support_ticket_user_id'), table_name='support_ticket')
    op.drop_table('support_ticket')
    op.drop_index(op.f('ix_oauth_account_user_id'), table_name='oauth_account')
    op.drop_table('oauth_account')
    op.drop_table('notification')
    op.drop_table('musician_profile')
    op.drop_index(op.f('ix_ensemble_member_password_setup_token'), table_name='ensemble_member')
    op.drop_index(op.f('ix_ensemble_member_member_user_id'), table_name='ensemble_member')
    op.drop_index(op.f('ix_ensemble_member_leader_user_id'), table_name='ensemble_member')
    op.drop_index(op.f('ix_ensemble_member_email'), table_name='ensemble_member')
    op.drop_table('ensemble_member')
    op.drop_index(op.f('ix_email_log_user_id'), table_name='email_log')
    op.drop_index(op.f('ix_email_log_template_slug'), table_name='email_log')
    op.drop_index(op.f('ix_email_log_status'), table_name='email_log')
    op.drop_index(op.f('ix_email_log_recipient'), table_name='email_log')
    op.drop_index(op.f('ix_email_log_created_at'), table_name='email_log')
    op.drop_table('email_log')
    op.drop_table('contractor_profile')
    op.drop_index(op.f('ix_user_password_reset_token'), table_name='user')
    op.drop_index(op.f('ix_user_email_verification_token'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('platform_payment_settings')
    op.drop_index(op.f('ix_email_template_slug'), table_name='email_template')
    op.drop_table('email_template')
    # ### end Alembic commands ###
